security:
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\Agents:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                #class: App\Entity\Agents
                class: App\Entity\User
                property: email
        app_agents_provider:
            entity:
                class: App\Entity\Agents
                property: email
        all_users:
            chain:
                providers: ['app_user_provider','app_agents_provider']

        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_admin:
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
                entry_point: App\Security\UserAuthenticator

        agents:
            anonymous: true
            lazy: true
            provider: app_agents_provider
            logout:
                path: app_logout_agents
            guard:
                authenticators:
                    - App\Security\AgentsAuthenticator

                entry_point: App\Security\AgentsAuthenticator
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
