INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (5, 'France', 'Francaise');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (6, 'Angleterre', 'Anglais');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (7, 'USA', 'Américain');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (8, 'Russie', 'Russe');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (9, 'Allemagne', 'Allemand');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (10, 'Maroc', 'Marocain');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (11, 'Turquie', 'Turque');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (12, 'Italie', 'Italien');
INSERT INTO erpmission.pays (id, libelle, nationalite) VALUES (13, 'Espagne', 'Espagnol');