-- MySQL Script generated by MySQL Workbench
-- Wed Feb 10 15:17:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pays` (
  `id_pays` INT NOT NULL,
  `libelle_pays` VARCHAR(45) NOT NULL,
  `nationalite_pays` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pays`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cibles` (
  `id_cible` INT NOT NULL AUTO_INCREMENT,
  `firstname_cible` VARCHAR(50) NOT NULL,
  `lastname_cible` VARCHAR(50) NOT NULL,
  `birthday_cible` DATETIME NOT NULL,
  `code_cible` INT(4) NOT NULL,
  `pays_cible` INT NOT NULL,
  PRIMARY KEY (`id_cible`, `pays_cible`),
  INDEX `fk_cibles_pays1_idx` (`pays_cible` ASC) VISIBLE,
  CONSTRAINT `fk_cibles_pays1`
    FOREIGN KEY (`pays_cible`)
    REFERENCES `mydb`.`pays` (`id_pays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`planques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planques` (
  `id_planque` INT NOT NULL AUTO_INCREMENT,
  `code_planque` INT(4) NOT NULL,
  `adresse_planque` VARCHAR(45) NOT NULL,
  `postal_planque` INT(10) NOT NULL,
  `ville_planque` VARCHAR(45) NOT NULL,
  `type_planque` VARCHAR(45) NOT NULL,
  `pays_planques` INT NOT NULL,
  PRIMARY KEY (`id_planque`, `pays_planques`),
  INDEX `fk_planques_nationalite_idx` (`pays_planques` ASC) VISIBLE,
  CONSTRAINT `fk_planques_nationalite`
    FOREIGN KEY (`pays_planques`)
    REFERENCES `mydb`.`pays` (`id_pays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typesusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`typesusers` (
  `id_typeuser` INT NOT NULL,
  `libelle_typeuser` VARCHAR(45) NULL,
  PRIMARY KEY (`id_typeuser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `role_user` VARCHAR(50) NOT NULL,
  `firstname_user` VARCHAR(50) NOT NULL,
  `lastname_user` VARCHAR(50) NOT NULL,
  `email_user` VARCHAR(50) NOT NULL,
  `password_user` VARCHAR(50) NOT NULL,
  `createdAt_user` DATETIME NOT NULL,
  `birthday_user` DATETIME NOT NULL,
  `code_user` INT(4) NOT NULL,
  `pays_user` INT NOT NULL,
  `type_user` INT NOT NULL,
  PRIMARY KEY (`id_user`, `pays_user`, `type_user`),
  INDEX `fk_users_pays1_idx` (`pays_user` ASC) VISIBLE,
  INDEX `fk_users_typesusers1_idx` (`type_user` ASC) VISIBLE,
  CONSTRAINT `fk_users_pays1`
    FOREIGN KEY (`pays_user`)
    REFERENCES `mydb`.`pays` (`id_pays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_typesusers1`
    FOREIGN KEY (`type_user`)
    REFERENCES `mydb`.`typesusers` (`id_typeuser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typesmissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`typesmissions` (
  `id_typemission` INT NOT NULL AUTO_INCREMENT,
  `libelle_typemission` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_typemission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statutsmissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statutsmissions` (
  `id_statutmission` INT NOT NULL AUTO_INCREMENT,
  `libelle_statutmission` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_statutmission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`specialites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`specialites` (
  `id_specialite` INT NOT NULL AUTO_INCREMENT,
  `libelle_specialite` VARCHAR(50) NULL,
  PRIMARY KEY (`id_specialite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missions` (
  `id_mission` INT NOT NULL AUTO_INCREMENT,
  `title_mission` VARCHAR(50) NOT NULL,
  `description_mission` LONGTEXT NOT NULL,
  `codename_mission` VARCHAR(50) NOT NULL,
  `datestart_mission` DATETIME NOT NULL,
  `dateend_mission` DATETIME NOT NULL,
  `type_mission` INT NOT NULL,
  `statut_mission` INT NOT NULL,
  `pays_mission` INT NOT NULL,
  `specialite_mission` INT NOT NULL,
  PRIMARY KEY (`id_mission`, `type_mission`, `statut_mission`, `pays_mission`, `specialite_mission`),
  INDEX `fk_missions_typesmissions1_idx` (`type_mission` ASC) VISIBLE,
  INDEX `fk_missions_statutsmissions1_idx` (`statut_mission` ASC) VISIBLE,
  INDEX `fk_missions_pays1_idx` (`pays_mission` ASC) VISIBLE,
  INDEX `fk_missions_specialites1_idx` (`specialite_mission` ASC) VISIBLE,
  CONSTRAINT `fk_missions_typesmissions1`
    FOREIGN KEY (`type_mission`)
    REFERENCES `mydb`.`typesmissions` (`id_typemission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missions_statutsmissions1`
    FOREIGN KEY (`statut_mission`)
    REFERENCES `mydb`.`statutsmissions` (`id_statutmission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missions_pays1`
    FOREIGN KEY (`pays_mission`)
    REFERENCES `mydb`.`pays` (`id_pays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missions_specialites1`
    FOREIGN KEY (`specialite_mission`)
    REFERENCES `mydb`.`specialites` (`id_specialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missions_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missions_has_users` (
  `mission_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`mission_id`, `user_id`),
  INDEX `fk_missions_has_users_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_missions_has_users_missions1_idx` (`mission_id` ASC) VISIBLE,
  CONSTRAINT `fk_missions_has_users_missions1`
    FOREIGN KEY (`mission_id`)
    REFERENCES `mydb`.`missions` (`id_mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missions_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_specialites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_specialites` (
  `user_id` INT NOT NULL,
  `specialite_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `specialite_id`),
  INDEX `fk_users_has_specialites_specialites1_idx` (`specialite_id` ASC) VISIBLE,
  INDEX `fk_users_has_specialites_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_specialites_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_specialites_specialites1`
    FOREIGN KEY (`specialite_id`)
    REFERENCES `mydb`.`specialites` (`id_specialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missions_has_planques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missions_has_planques` (
  `mission_id` INT NOT NULL,
  `planque_id` INT NULL,
  PRIMARY KEY (`mission_id`, `planque_id`),
  INDEX `fk_missions_has_planques_planques1_idx` (`planque_id` ASC) VISIBLE,
  INDEX `fk_missions_has_planques_missions1_idx` (`mission_id` ASC) VISIBLE,
  CONSTRAINT `fk_missions_has_planques_missions1`
    FOREIGN KEY (`mission_id`)
    REFERENCES `mydb`.`missions` (`id_mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missions_has_planques_planques1`
    FOREIGN KEY (`planque_id`)
    REFERENCES `mydb`.`planques` (`id_planque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missions_has_cibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missions_has_cibles` (
  `mission_id` INT NOT NULL,
  `cible_id` INT NOT NULL,
  PRIMARY KEY (`mission_id`, `cible_id`),
  INDEX `fk_missions_has_cibles_cibles1_idx` (`cible_id` ASC) VISIBLE,
  INDEX `fk_missions_has_cibles_missions1_idx` (`mission_id` ASC) VISIBLE,
  CONSTRAINT `fk_missions_has_cibles_missions1`
    FOREIGN KEY (`mission_id`)
    REFERENCES `mydb`.`missions` (`id_mission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missions_has_cibles_cibles1`
    FOREIGN KEY (`cible_id`)
    REFERENCES `mydb`.`cibles` (`id_cible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
