INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (6, 1, '55, boulevard de Bertrand', 56275, 'Gerard', 5, 5);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (7, 2, '430, impasse Devaux', 13367, 'HoareauVille', 5, 6);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (8, 3, '15030 Wiegand Points Suite 867', 47969, 'Murrayfort', 7, 7);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (9, 4, '318 Schumm Knoll', 22081, 'Kohlertown', 7, 6);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (10, 6, '11 Cremin Line', 6818, 'Corbinston', 6, 5);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (11, 7, '7 Colby Close', 6705, 'Felipeston', 6, 10);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (12, 8, '84342 Gottlieb Vista Apt. 970', 62750, 'Jonathonville', 8, 5);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (13, 9, 'Jónás játszótér 17. 58. ajtó', 7588, 'Hódmezővásárhely', 8, 7);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (14, 11, 'Wanda-Reinhardt-Straße 53a', 53635, 'Husum', 9, 7);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (15, 12, 'Björn-Reimann-Straße 261', 31211, 'Burgdorf', 9, 6);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (16, 13, '7140 طريق حنان جواهرجي', 78209, 'الطائف', 10, 10);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (17, 14, '77400 ممر نائله الصامل عمارة رقم 27', 51871, 'مكة', 10, 6);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (18, 15, '250 rue emile Zola', 56235, 'Milan', 12, 6);
INSERT INTO erpmission.planques (id, code, adresse, postal, city, paysplanque_id, typeplanque_id) VALUES (19, 16, '562 ,rue escobar', 89622, 'Madrid', 13, 7);